name: test

on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  id-token: write   # Required to request the OIDC JWT
  contents: read    # Required to checkout the repository

jobs:
  Listing_buckets:
    runs-on: ubuntu-latest
    steps:
      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: List S3 Buckets
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: 
          echo "Listing S3 Buckets in region $AWS_REGION"
          aws s3 ls --region $AWS_REGION
